---

#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# -- This is the default, you can also use requarks/wiki
image:
  # -- image repository
  repository: aler9/rtsp-simple-server
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-wikijs#environment-variables-e) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Amsterdam

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      # -- Configure Web interface + API port
      # @default -- See values.yaml
      http:
        port: 1935
        enabled: true
        protocol: TCP
      # -- Configure rtsp port used for camera device
      # @default -- See values.yaml
      rtsp:
        enabled: true
        port: 8554
        protocol: TCP

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data
    accessMode: ReadWriteOnce	
    size: 1Gi
