---
apiVersion: v2
appVersion: 0.1
description: MariaDB opensource database system
name: MariaDB
version: 0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - eufy
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/wikijs
icon: https://static.requarks.io/logo/wikijs-butterfly.svg
sources:
  - https://hub.docker.com/r/linuxserver/wikijs/
  - https://github.com/Requarks/wiki
maintainers:
  - name: rolfberkenbosch
    email: rolf@berkenbosch.nl
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
