---

#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# -- This is the default, you can also use requarks/wiki
image:
  # -- image repository
  repository: mariadb
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: Always

# -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-wikijs#environment-variables-e) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: Europe/Amsterdam
  USERNAME: username
  MARIADB_ROOT_PASSWORD: password
  MARIADB_DATABASE: databasename
  MARIADB_USER: databaseusername
  MARIADB_PASSWORD: databasepassword

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      tcp:
        port: 3306
        eanbled: true
        protocol: TCP

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /var/lib/mysql
    accessMode: ReadWriteOnce	
    size: 1Gi
